### ISSUE TITLE
hardcoded column-names 

### ISSUE THREAD

**Issue by frankcorneliusmartin** [TNO-MPC/protocols.kaplan_meier#1]
The `event` and `time` column names are hardcoded in the `Alice` class:

https://github.com/TNO-MPC/protocols.kaplan_meier/blob/ee120eea7668bec71b3c436e9f059dfd4caa19f5/tno/mpc/protocols/kaplan_meier/data_owner.py#L188

https://github.com/TNO-MPC/protocols.kaplan_meier/blob/ee120eea7668bec71b3c436e9f059dfd4caa19f5/tno/mpc/protocols/kaplan_meier/data_owner.py#L323-L325

Would it be possible to have these settable on initialization?

**Comment by ThomasTNO** [comment]
Nice suggestion, Frank! Thanks.

We will process this and release a new version.

The release will take place together with new releases of some (nested) dependencies.

**Comment by ThomasTNO** [comment]
Solved in https://github.com/TNO-MPC/protocols.kaplan_meier/commit/630682f25bc23be68238288a5bc796246382ee8a
