### ISSUE TITLE
Use of a single port instead of two 

### ISSUE THREAD

**Issue by frankcorneliusmartin** [TNO-MPC/protocols.kaplan_meier#2]
The algorithm requires to run on two ports. It seems like it can easily be changed to using a single port by adding the following statement to the `Alice` and `Bob`  `start_protocol` method. This would require to change: 

https://github.com/TNO-MPC/protocols.kaplan_meier/blob/ee120eea7668bec71b3c436e9f059dfd4caa19f5/tno/mpc/protocols/kaplan_meier/data_owner.py#L260-L261

and
 
https://github.com/TNO-MPC/protocols.kaplan_meier/blob/ee120eea7668bec71b3c436e9f059dfd4caa19f5/tno/mpc/protocols/kaplan_meier/data_owner.py#L501-L502

to 
```python
await self.receive_share() 
await self.pool.shutdown()
await self.run_mpyc() 
```

I tested this locally and that worked. Would it make sense to include that in the source?

**Comment by ThomasTNO** [comment]
Nice suggestion. This seems fine to me as the pool is only used in the first part of the protocol.

**Comment by frankcorneliusmartin** [comment]
I encounter an issue with the by me suggested change. It seems like the `Alice` worker closes the connection premature in some cases. 

I temporary worked around by this by adding a `time.sleep` in the Alice worker before shutting the server down. 

Do we have information from the other party when the connection can safely closed? Not sure if that is even possible.

**Comment by ThomasTNO** [comment]
> I encounter an issue with the by me suggested change. It seems like the `Alice` worker closes the connection premature in some cases.
> 
> I temporary worked around by this by adding a `time.sleep` in the Alice worker before shutting the server down.
> 
> Do we have information from the other party when the connection can safely closed? Not sure if that is even possible.

I was just about to start testing this, will let you know!

**Comment by ThomasTNO** [comment]
The issue encountered is an unsolvable race-condition when exiting one communication channel (tno.mpc.communication) and switching to a new communication channel on the same port (MPyC). If one player starts communicating over the new channel (expecting that the other players are ready to start communicating), but they didn't switch to the new communication channel yet, stuff will (and should) break.

Also decided not to implement the shutdown as that modifies the communication pool (that is potentially in use for other analyses as well).
